services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactional_outbox_and_inbox_example
    ports:
      - 5001:5432
    volumes:
      # https://github.com/docker-library/docs/blob/master/postgres/README.md#pgdata
      - postgres_data_volume:/var/lib/postgresql/data
      # https://github.com/docker-library/docs/blob/master/postgres/README.md#initialization-scripts
      - ./middlewares/postgres/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 3

  pubsub-emulator:
    platform: linux/amd64
    init: true
    build:
      context: ./middlewares/pubsub
      dockerfile: Dockerfile
    environment:
      - PUBSUB_PROJECT_ID=my-project
      - PUBSUB_TOPIC_ID=my-topic
      - PUBSUB_SUBSCRIPTION_ID=my-subscription
      - PUBSUB_EMULATOR_HOST=0.0.0.0:5002
    restart: always
    ports:
      - 5002:5002

volumes:
  postgres_data_volume:
