services:
  postgres:
    build:
      context: ./middlewares/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactional_outbox_and_inbox_example
    ports:
      - 5001:5432
    volumes: # https://github.com/docker-library/docs/blob/master/postgres/README.md
      - postgres_data_volume:/var/lib/postgresql/data
      - ./middlewares/postgres/initdb.d:/docker-entrypoint-initdb.d
      - ./middlewares/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    restart: always
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1
      start_period: 5s
      interval: 10s
      timeout: 10s
      retries: 3

  pubsub-emulator:
    platform: linux/amd64
    init: true
    build:
      context: ./middlewares/pubsub
      dockerfile: Dockerfile
    environment:
      - PUBSUB_PROJECT_ID=my-project
      - PUBSUB_TOPIC_ID=my-topic
      - PUBSUB_SUBSCRIPTION_ID=my-subscription
      - PUBSUB_EMULATOR_HOST=0.0.0.0:5002
    restart: always
    ports:
      - 5002:5002

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config", "/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317"    # OTLP - localhost apps to container collector
      - "8889:8889"    # Prometheus Exporter - for debugging from browser
    volumes:
      - ./middlewares/otel-collector/otel-collector-config.yml:/etc/otelcol/config.yaml
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.65.0
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      # If you want to change the jaeger's default OTLP port(4317), use --collector.otlp.grpc.host-port flag.
      - "16686:16686"  # Jaeger UI

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"   # Prometheus UI
    volumes:
      - ./middlewares/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  postgres_data_volume:
