// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

type Querier interface {
	InsertInboxMessage(ctx context.Context, arg InsertInboxMessageParams) (InboxMessage, error)
	InsertOutboxMessage(ctx context.Context, messagePayload json.RawMessage) (OutboxMessage, error)
	SelectUnprocessedInboxMessage(ctx context.Context) (InboxMessage, error)
	SelectUnsentOutboxMessages(ctx context.Context, limit int32) ([]OutboxMessage, error)
	UpdateInboxMessageAsProcessed(ctx context.Context, messageUuid uuid.UUID) (InboxMessage, error)
	UpdateOutboxMessageAsSent(ctx context.Context, messageUuid uuid.UUID) (OutboxMessage, error)
}

var _ Querier = (*Queries)(nil)
