// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"
)

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, message_type, message_payload, message_status, created_at, updated_at FROM message_outbox
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (MessageOutbox, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i MessageOutbox
	err := row.Scan(
		&i.ID,
		&i.MessageType,
		&i.MessagePayload,
		&i.MessageStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
