// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetMessageByID(ctx context.Context, id int64) (MessageOutbox, error)
}

var _ Querier = (*Queries)(nil)
