// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type InboxMessage struct {
	MessageUuid    uuid.UUID
	MessagePayload []byte
	ReceivedAt     pgtype.Timestamp
	ProcessedAt    pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type OutboxMessage struct {
	MessageUuid    uuid.UUID
	MessagePayload []byte
	SentAt         pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
