// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type InboxMessage struct {
	ID          uuid.UUID
	Payload     []byte
	ReceivedAt  time.Time
	ProcessedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type OutboxMessage struct {
	ID        uuid.UUID
	Payload   []byte
	SentAt    *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}
